apiVersion: v2
name: kubebrowser
description: Allow whitelisted people to access your kubeconfigs
type: application
version: 0.5.0
appVersion: "0.5.0"
dependencies:
  - name: common
    version: 2.30.0
    repository: oci://registry-1.docker.io/bitnamicharts
